language: go
dist: xenial
os:
- linux
go:
- 1.15
deploy:
  provider: script
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
env:
  global:
    secure: Iv9tcF2W4QPA3j1OHQRVQkLUz5r3jgbD8uxhClmEWLNABSBeQSNrEsI42ZSFgeNG7UIiy8gR2mtN3JRy0evvXyAIQRVHFuNf4bDcIg54e9NDdcq/qZc/4FG31PZ8P95h2hqREfYeRNj2ydujrQYLlboUM1XPscWsIrkewbxhAdIhfirWNMLhZ3+XnQEu0dP5ZEGqRUo0k0zRxEvIqofaCwUTdA/xVROfmJOijAy9C+iF0SQHax7ri/yHlvoc1b4rNjzlAtLBNtGYsee6laLa6uVm+sO6Ge5OcUJC1lYp1gnbfC/wXKuS/Fruppdbmz337o+nUUZsH4bXDF2DqNGaHGg9Lgb5+fpvT4o0Il3ivaupPEhTDwr52gxZ0JeYK7E35Uec9QSF7k/Z+fczLsrlJKr2fsmr+/5grwOelnWkDaGiXn8H56NM9ztUd/1w5JTe7a8DPxk1Szap27pO7qVO/9kf40oR9BaPOv2evmMW61dWJEYKCudR5jxVqPL7bBrKMG/6VcBVru1sbuzUGyJ+w+PN2hXVmYMl3Om9WJVO7dwSfVlVXPUDV5txnIqSCBBUz/9eQoAM0aT/LyNGD+qIr5013NUPFgp40ocJIDi5hMWIXQgatowOSJPnPiYUtArP7/36V8xITy3b6LFuZm+I42jZ0H3scCf2YxPYYNUFyKw=
